# VM command

name: Manual Trigger
on:
  push:
    branch:
      - main


  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: choice
        description: "Select environment. dev, qa, prod"
        options:
          - "dev"
          - "qa"
          - "prod"
      REGION:
        required: true
        type: choice
        description: "Select region. WUS, WEU"
        options:
          - "WUS"
          - "WEU"


permissions:
  issues: write

jobs:
  ShowInputs:


    runs-on:
      labels:
        - "self-hosted"

    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v3

      #      - name: "Run Snyk to check for vulnerabilities"
      #        uses: snyk/actions/node@master
      #        env:
      #          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: ZAP Scan
#        uses: zaproxy/action-full-scan@v0.10.0
#        with:
#          token: ${{ secrets.MY_GITHUB_TOKEN }}
#          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
#          target: 'https://www.zaproxy.org/'
#          rules_file_name: '.zap/rules.tsv'
#          cmd_options: '-a'

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: "Mock"
        run: |
          echo ${{ inputs.ENVIRONMENT }} && \
          echo ${{ inputs.REGION }}


#      - name: "Artifact"
#        uses: actions/upload-artifact@v2
#        with:
#          name: "test"
#          path: "test.txt"

      - name: "Test"
        run: |
          echo "done"
